### ISSUE TITLE
Zambian trial of EGDT using jugular venous assessment

### ISSUE THREAD

**Issue by badgettrg** [openMetaAnalysis/Early-goal-directed-therapy-for-septic-shock#3]
Should we include the Zambian trial by Andrews (1). It is a trial of EGDT albeit with unusual monitoring. I suggest we include it due to meeting criteria, but then make an ad hoc decision to exclude it from pooling due to unusual protocol. However, include in the discussion as exemplifying the perils of having **no** access to central venous catheterization.
# References
1. Andrews B, Muchemwa L, Kelly P, Lakhi S, Heimburger DC, Bernard GR. Simplified
   severe sepsis protocol: a randomized controlled trial of modified early goal-directed therapy in Zambia. Crit Care Med. 2014 Nov;42(11):2315-24. doi: [10.1097/CCM.0000000000000541](http://dx.doi.org/10.1097/CCM.0000000000000541). PMID: 2[5072757](http://pubmed.gov/25072757); PMCID: [PMC4199893](http://pubmedcentral.gov/PMC4199893/)

**Comment by yhussein** [comment]
Hey Dr Badgett
very interesting study, i personally don't see how the study fit with the other already included
both arms are kind of usual car arm one with protocol and one without, both did not have hemodynamic monitoring.
not to mention 80% of the patient were HIV positive with a median CD4 of 40 (this is was an exclusion criteria in the ProCESS and ARISE and River trials)
if you mean by met the criteria (included patient with sever sepsis) i think you have a point to say it came up in our search, then excluded due to the nature of the intervention and specificity of the population in hand

**Comment by mgaines1978** [comment]
Youness you have a good point and noticed the HIV and Tb but not the exclusion criteria in other studies

Sent from my iPhone

On Feb 12, 2015, at 11:30 AM, yhussein <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey Dr Badgett
very interesting study, i personally don't see how the study fit with the other already included
both arms are kind of usual car arm one with protocol and one without, both did not have hemodynamic monitoring.
not to mention 80% of the patient were HIV positive with a median CD4 of 40 (this is was an exclusion criteria in the ProCESS and ARISE and River trials)
if you mean by met the criteria (included patient with sever sepsis) i think you have a point to say it came up in our search, then excluded due to the nature of the intervention and specificity of the population in hand

**Comment by badgettrg** [comment]
So, lets exclude, but think further whether ok to cite in the discussion.

Various reasons why mortality might be higher; however, why was mortality higher (not quite significantly so, but enough they stopped the trial) in patients with baseline hypoxic respiratory failure? Does this trial illustrate what happens if you overreact to PROCESS and ARISE and conclude that central lines are not needed - rather than concluding central lines are not required?

Bob

**Comment by badgettrg** [comment]
**Resolution**: we excluded this trial, but may cite in the discussion of the paper as demonstrating a scenario where there may be benefit from central venous catheterization (CVC): among patients with respiratory distress, aggressive fluids without CVC monitoring may be harmful.
